import 'package:mdi/mdi.dart';

Map<String, dynamic> mdiIcons = {
  'A': Mdi.alphaACircle,
  'B': Mdi.alphaBCircle,
  'C': Mdi.alphaCCircle,
  'D': Mdi.alphaDCircle,
  'E': Mdi.alphaECircle,
  'F': Mdi.alphaFCircle,
  'G': Mdi.alphaGCircle,
  'H': Mdi.alphaHCircle,
  'I': Mdi.alphaICircle,
  'J': Mdi.alphaJCircle,
  'K': Mdi.alphaKCircle,
  'L': Mdi.alphaLCircle,
  'M': Mdi.alphaMCircle,
  'N': Mdi.alphaNCircle,
  'O': Mdi.alphaOCircle,
  'P': Mdi.alphaPCircle,
  'Q': Mdi.alphaQCircle,
  'R': Mdi.alphaRCircle,
  'S': Mdi.alphaSCircle,
  'T': Mdi.alphaTCircle,
  'U': Mdi.alphaUCircle,
  'V': Mdi.alphaVCircle,
  'W': Mdi.alphaWCircle,
  'X': Mdi.alphaXCircle,
  'Y': Mdi.alphaYCircle,
  'Z': Mdi.alphaZCircle
};
